accountapp/urls.py
from re import template
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from . import views

app_name = 'accountapp'


urlpatterns = [

    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('create/', views.AccountCreate, name="create"),
    path('detail/<int:pk>', views.AccountDetailView.as_view(), name="detail"),
]

buildapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
# from accountapp.views import AccountCreateView
from buildapp.views import community, home, write_poet, write_sentence

app_name = 'buildapp'

urlpatterns = [
    path('', home, name='home'),
    path('poet/write', write_poet, name="write_poet"),
    path('community', community, name="community"),
    path('sentence/write', write_sentence, name="write_sentence"),
]

profileapp/urls.py
from django.urls import path


from profileapp import views

app_name = 'profileapp'

urlpatterns = [
    path('mypage/', views.MyPage, name='mypage'),
    path('create/', views.ProfileCreate, name='create'),
]

today/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('buildapp.urls')),
    path('accounts/', include('accountapp.urls')),
    path('profile/', include('profileapp.urls')),

]

accountapp/models.py
from django.db import models

# Create your models here.

buildapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from profileapp.models import Profile


class Article(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)

    title = models.CharField(max_length=100, null=True)
    text = models.TextField(null=False)
    created_at = models.DateTimeField(auto_now=True)

class Sentence(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='sentence', null=True)

    text = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now=True)

profileapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')

    image = models.ImageField(upload_to='profile/', null=True)
    nickname = models.CharField(max_length=20, unique=True, null=True)
    message = models.CharField(max_length=100, null=True)




#class Article(models.Model):
#    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='article', null=True)
#    info = models.ForeignKey(Profile, on_delete=models.SET_NULL, related_name='article', null=True)
#
#    title = models.CharField(max_length=100, null=True)
#    text = models.TextField(null=False)
#    created_at = models.DateTimeField(auto_now=True)

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User



class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', 'email')

buildapp/forms.py
from django.forms import ModelForm

from buildapp.models import Sentence, Article


class SentenceCreationForm(ModelForm):
    class Meta:
        model = Sentence
        fields = ['text', 'writer']



class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['title', 'text']

profileapp/forms.py
from django.forms import ModelForm


from accountapp import forms
from profileapp.models import Profile
from django.contrib.auth.forms import UserChangeForm

class ProfileCreationForm(ModelForm):

    class Meta:
        model = Profile
        fields = ['image', 'nickname', 'message']

accountapp/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django.views.generic.list import MultipleObjectMixin

from accountapp.forms import UserForm


# Create your views here.
from profileapp.models import Profile


def AccountCreate(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('profileapp:create')  # 바꿔야
    else:
        form = UserForm()
    return render(request, 'accountapp/create.html', {'form': form})



class AccountDetailView(DetailView, MultipleObjectMixin):
    model = Profile
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'

buildapp/views.py
from asyncore import write
from sqlite3 import Time

from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.generic import CreateView

from buildapp.forms import SentenceCreationForm
from buildapp.models import Article, Sentence


def home(request):
    return render(request, 'buildapp/home.html')


@login_required(login_url='/accounts/login/')
def write_sentence(request): 
    if request.method == 'GET' :
        return render(request, 'buildapp/write_sentence.html')

    if request.method == 'POST' :
        list_sentence = request.POST.getlist('sentence[]') # 선택되지 않은 문장 가져오기 
        
        list_selected = request.POST.getlist('selectedSentence[]') # 선택된 문장 가져오기 

        writer = request.user
        return render('buildapp/write_page.html', {'list_selected':list_selected})


@login_required(login_url='/accounts/login/')
def write_poet(request):

    # articles = Article.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title', False)
        text = request.POST.get('text', False)

        writer = request.user

        article = Article()
        article.title = title
        article.text = text
        article.writer = writer
        article.save()

        return render(request, 'profileapp/mypage.html')

    return render(request, 'buildapp/write_page.html')


def community(request):
    return render(request, 'buildapp/tst_write_community.html')

profileapp/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views.generic import DetailView, CreateView
from django.views.generic.list import MultipleObjectMixin


from profileapp.forms import ProfileCreationForm


#def Create(request):
#    if request.method == 'GET':
#        return render(request, 'profileapp/create.html')
# def Create(request):
#     if request.method == "POST":
#         form = ProfileCreationForm(request.POST)
#         if form.is_valid():
#             form.save()
#             nickname = form.cleaned_data.get('nickname')
#             return redirect('buildapp:home')
#     else:
#         form = ProfileCreationForm()
#     return render(request, 'profileapp/create.html', {'form': form})
#
#
# class Nickname:
#     pass


def Create(request):

    if request.method == 'POST':
        Nickname = request.POST.get('nickname', False)


        nickname = Nickname()

        nickname.save()

        return render(request, 'buildapp:home')

    return render(request, 'profileapp/create.html')



from profileapp.models import Profile




def MyPage(request):
    return render(request, 'profileapp/mypage.html')


def ProfileCreate(request):
    if request.method == 'POST':

        profile = Profile()
        profile.user = request.user
        profile.nickname = request.POST['nickname']
        profile.message = request.POST['message']
        profile.save()













#def profile_update_view(request):
#    if request.method == 'POST':
#        user_change_form = CustomCsUserChangeForm(request.POST, instance = request.user)
#
#        if user_change_form.is_valid():
#            user_change_form.save()
#            return render(request, 'users/profile.html')
#    else:
#        user_change_form = CustomCsUserChangeForm(instance = request.user)
#
#        return render(request, 'users/profile_update.html', {'user_change_form':user_change_form})

        return redirect('buildapp:home')
    return render(request, 'profileapp/create.html')

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/account.css' %}">


    <div class="cont_wrap" style="border-top:solid 0.2rem #000;">

        <div class="title_wrap">
            <h2>회원가입</h2>
        </div>

        <form action="{% url 'accountapp:create' %}" method="post" class="signup-wrap">
            {% csrf_token %}

            {% include "accountapp/forms_errors.html" %}

            <div>
                <label for="username" class="create-account">
                    아이디
                </label>
                <input type="text" class="account-box" name="username" id="username" placeholder="아이디" value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div>
                <label for="password1" class="create-account">
                    비밀번호
                </label>
                <input type="password" class="account-box" name="password1" id="password1" placeholder="8자리 이상의 비밀번호로 생성해주세요." value="{{ form.password1.value|default_if_none:'' }}">
            </div>
            <div>
                <label for="password2" class="create-account">
                    비밀번호 재입력
                </label>
                <input type="password" class="account-box" name="password2" id="password2" placeholder="비밀번호 재입력" value="{{ form.password2.value|default_if_none:'' }}">
            </div>
            <div>
                <label for="email" class="create-account">
                    이메일 주소
                </label>
                <input type="text" class="account-box" name="email" id="email" placeholder="이메일 주소" value="{{ form.email.value|default_if_none:'' }}">
            </div>
            <button type="submit" class="submit-btn">생성하기</button>
        </form>
    </div>

    <script>
        element = document.querySelector("#"+label);
        element.focus();
        element.setAttribute('style', 'border: 3px solid #CC3F3B;');
        const error = message ? message : "올바른 값을 입력해주세요.";
        element.setAttribute('placeholder', error);
    </script>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">

    <div>
        <div style="text-align: center; max-width: 500px; margin: 4rem auto;">


            {% if target_user.profile %}
            <img src="{{ target_user.profile.image.url }}" alt=""
                 style="height: 12rem; width: 12rem; border-radius: 20rem; margin-bottom: 2rem">
            <h2>
                {{ target_user.profile.nickname }}
            </h2>
                <h6>
                    {{ target_user.profile.message }}
                </h6>
            {% if target_user == user %}
            <h2>
                <br>
            </h2>
            {% endif %}
            {% else %}
{#                {% if target_user == user %}#}
{#                    <a href="{% url 'profileapp:create' %}" class="btn btn-dark rounded-pill col-6 mb-1">#}
{#                        <h2 style="font-family: 'NanumSquareB">#}
{#                            Create Profile#}
{#                        </h2>#}
{#                    </a><br>#}
{##}
{#                {% else %}#}
{#                    <h2>#}
{#                        닉네임 미설정#}
{#                    </h2>#}
{#                {% endif %}#}
            {% endif %}


{##}
{#            {% if target_user == user %}#}
{#            <a href="{% url 'accountapp:delete' pk=user.pk%}" style="margin-bottom: 1rem;" class="btn btn-danger rounded-pill col-3">#}
{#                <h6>#}
{#                    Change Info#}
{#                </h6>#}
{#            </a>#}
{#            <a href="{% url 'accountapp:delete' pk=user.pk%}" style="margin-bottom: 1rem;" class="btn btn-danger rounded-pill col-3">#}
{#                <h6>#}
{#                    Quit#}
{#                </h6>#}
{#            </a>#}


            {% endif %}

        </div>

    </div>
{##}
{#            <div>#}
{##}
{#                {% include 'snippets/list_fragment.html' with article_list=object_list %}#}
{##}
{#            </div>#}


{% endblock %}

accountapp/templates/accountapp/forms_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}

<div class="">
    {% for field in form %}

    <!-- 필드 오류 -->
    {% if field.errors %}
    <script>
        var tmp = "";
        if ( "{{ field.label }}" == 'Username'){
            tmp = 'username';
        } else if ( "{{ field.label }}" == 'Password' ) {
            tmp = 'password1';
        } else if ( "{{ field.label }}" == 'Password confirmation' ) {
            tmp = 'password2';
        } else {
            tmp = 'email';
        }

        var label =  tmp;
    </script>
    {% endif %}
    {% endfor %}

    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <script>
        var message = "{{ error }}";
    </script>
    {% endfor %}
</div>
{% endif %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/account.css' %}">

    <div class="login-wrap">
        <div>
            <div class="title-wrap">
                <p class="cont_logo">&lt;오늘:의 문장&gt;</p>
            </div>
            <form action="{% url 'accountapp:login' %}" method="post" class="login-form">
                {% csrf_token %}
                {% include "accountapp/forms_errors.html" %}
                <div>
                    <label for="id" class="create-account">
                        아이디
                    </label>
                    <input type="text" class="account-box" name="username" id="username" placeholder="아이디" value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div>
                    <label for="password" class="create-account">
                        비밀번호
                    </label>
                    <input type="password" class="account-box" name="password" id="password" placeholder="비밀번호" value="{{ form.password.value|default_if_none:'' }}">
                </div>
                <div>
                    <button type="submit" class="submit-btn">로그인</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}

  <div style="text-align: center; max-width: 500px; margin: 4rem auto">
    <div class="mb-4">
      <h4>Change Info</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      {% bootstrap_form form %}
      <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
  </div>

{% endblock %}

buildapp/templates/buildapp/home.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">

    <body>
        <div class="home_wrap">
            <div class= "main_warp">
                <div class="main_cont" data-aos="fade-up" data-aos-duration="600">
                    <h1 class= "main_title">글쓰기의 첫 걸음,</h1>
                    <h1 class= "main_title">오늘의 한 문장부터</h1>
                    <div style="text-align: center; margin-top: 40px">
                        <a href="{% url "buildapp:write_sentence" %}" class="home_btn">시작하기</a>
                    </div>

                </div>
            </div>

            <div class="home_ex_wrap">
                <div class="home_ex" data-aos="fade-up" data-aos-offset="300">
                    <p>모든 글은 한 문장에서 시작해요</p>
                    <p>문장을 창작하고, 문장을 공유하며</p>
                    <p>&lt;오늘:의 문장&gt;에서 글쓰기를 시작해보세요</p>
                </div>
            </div>


            <div class="home_guide_wrap" style="background: url('https://images.unsplash.com/photo-1600025281567-c17cede2ff92?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1770&q=80');"> 
                <div class= "home_guide" data-aos="fade-right" data-aos-offset="300" data-aos-easing="ease-out-sine"  style="text-align: left; padding: 200px 0 0 60px;">
                    <p class="guide_title">문장 쓰기 가이드</p>
                    <p class="guide_sub">평범한 문장을 </br>특별하게 바꿔보세요</p>
                    <p class= "guide_cont">문장 작성 가이드를 참고하여</br>평범했던 문장을</br>목적에 맞게</br>바꿀 수 있어요</p>
                </div>
            </div>

            <div class="home_guide_wrap dark" style="background: url('https://images.unsplash.com/photo-1614791962365-7590111b1b1c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1769&q=80');">
                <div class= "home_guide right-aos" data-aos="fade-left" data-aos-offset="300" data-aos-easing="ease-in-sine">
                    <p class="guide_title">문장 공유</p>
                    <p class="guide_sub">쓰지 않는 문장을 </br>다른 사람들과 공유해보세요</p>
                    <p class="guide_cont">글에 쓰이지 않은 문장들은</br>문장 공유 게시판에 올라가</br>다른 사람들에게 영감을</br>줄 수 있어요</p>
                </div>
            </div>

            <div class="home_btn_container" style="background: url('https://images.unsplash.com/photo-1600172454520-134a542a2255?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1548&q=80');">
                <h1 class="main_title" style="padding-top: 70px">
                    오늘도 어제도 아니 잊고
                </h1>
                <h1 class="main_title">
                    먼 훗날 그 때에 "잊었노라"
                </h1>
                <p class="guide_cont">
                    - 김소월, &lt;먼 훗날&gt;
                </p>
                <a href="{% url 'buildapp:write_poet' %}" class="home_btn">글쓰기</a>
                <a href="{% url 'buildapp:write_sentence' %}" class="home_btn">문장쓰기</a>
            </div>
            <hr>

        </div>
        
        <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
        <script>
          AOS.init();
        </script>



    </body>
{% endblock %}

buildapp/templates/buildapp/write_page.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/write_poet.css' %}">

<div class="form-wrapper">

    <form action="{% url 'buildapp:write_poet' %}" enctype="multipart" id='writePoet'/>

        {% csrf_token %}
        <div class= "text-area">
            <input class="title-input" type="text" placeholder="제목" name="title">
            <hr>
            <div class="sentence-box">
                <div class="sentence-area">
                    <p class="sentence-text random-sentence">나보기가 역겨워 가실 때에는 말없이 고이 보내 드리오리다</p>
                    <p class="sentence-text creator">원작자 : 김소월(ilovemunhak)</p>
                </div>
                <span class="icon-area">
                    <button id="plus"><i class="fa-solid fa-plus fa-lg icon-btn"></i></button>
                    <button id="rotate"><i class="fa-solid fa-arrows-rotate fa-lg icon-btn"></i></button>
                </span>
            </div>

            <textarea name="text-input" id="editor" placeholder="당신만의 이야기를 적어주세요." name="text"></textarea>
            <input type="hidden" name="text" id="text"/>
        </div>
        <div class="button-area">
            <button class="submit-button" id="poetSubmit">게시하기</button>
        </div>
    </form>
</div>

<!-- Ckeditor -->
<script>
    const sentences = [
        "나보기가 역겨워 가실 때에는 말없이 고이 보내 드리오리다",
        "문장 1", 
        "문장 2", 
    ];
    const creators = [
        "김소월(ilovemunhak)",
        "원작자 1",
        "원작자 2",
    ]; 

    var sentence = "";
    var creator = "";

    function randomIdx() {
        return Math.floor( Math.random() * sentences.length );
    };

    // 문장 랜덤 추출
    function randomSentence(e) {
        e.preventDefault(); 

        let idx = randomIdx();
        sentence = sentences[idx];
        creator = creators[idx];

        document.querySelector(".random-sentence").innerHTML = sentence;
        document.querySelector(".creator").innerHTML = "원작자 : " + creator;
    }

    // 초기화
    let idx = randomIdx();
    sentence = sentences[idx];
    creator = creators[idx];

    document.querySelector(".random-sentence").innerHTML = sentence;
    document.querySelector(".creator").innerHTML = "원작자 : " + creator;

    document.querySelector("#rotate").addEventListener("click", function(){ randomSentence(event) });

    // editor 
    let editor; 

    ClassicEditor
        .create( document.querySelector('#editor'), {
            removePlugins: ['Heading', '|','Table toolbar'],
            language: "ko"
        })
        .then(newEditor=>{
            // console.log(newEditor);
            editor = newEditor;
            // editor.setData('안녕');

            function applyText() {
                var text = editor.getData().replace('<p>', '').replace('</p>', '');
                document.querySelector("#text").value = text;
                document.forms.writePoet.method = "post";
                document.forms.writePoet.submit();
            }

            function addSentence(e) {
                e.preventDefault();
                editor.setData(sentence);
            }

            document.querySelector('#poetSubmit').addEventListener("click", applyText);
            document.querySelector("#plus").addEventListener("click", function(){ addSentence(event) });
        })
        .catch(error=>{
            console.error(error);
        });


</script>

{% endblock %}

profileapp/templates/profileapp/account_change.html
<html>
    <head>

    </head>
    <body>
        
    </body>
</html>

profileapp/templates/profileapp/mypage.html
{% extends 'base.html' %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/mypage.css' %}">

<style>
    .profile-detail-wrap {
        background-color: #d9d9d9;
        width: 15rem;
        height: 20rem;
        margin: 2rem;
    }
    


</style>


<body>
    <div class="mypage_wrap">
        <div class="title_wrap">
            <p class="cont_logo" style="text-align: left; font-family: 'Song Myung', serif;">&lt;오늘:의 문장&gt;</p>
        </div>
        <div>
            <p class="mypage_title">
                반갑습니다. {{ user.username }}님!
            </p>
        </div>
        <hr>
        <div class="profile-wrap" style="display:flex ;">
            <div class="profile-detail-wrap" style="flex:1 ;">
                <div class="profile-img">
                    {{ user.image }}
                </div>
                <div class="profile-text">
                    <div>
                        {{ user.nickname }}
                        {{ user.message }}
                    </div>

                </div>     
            </div>
            <div class="profie-nav" style="flex:1 ;">
                <div class="profile_item_wrap">
                    <a href="{% url 'buildapp:write_sentence' %}" class="profile_item">문장쓰기</a>
                </div>
                <div class="profile_item_wrap">
                    <a href="" class="profile_item">작성한 문장</a>
                </div>
                <div class="profile_item_wrap">
                    <a href="" class="profile_item">작성한 게시글</a>
                </div>
                <div class="profile_item_wrap">
                    <a href="{% url 'accountapp:detail' pk=user.pk %}" class="profile_item">개인정보관리</a>
                </div>
                <div class="profile_item_wrap">
                    <a href="{% url 'accountapp:logout' %}" class="profile_item">로그아웃</a>
                </div>    
            </div>
            
        </div>
    </div>
</body>

{% endblock %}

profileapp/templates/profileapp/profile.html
<!-- templates/profileapp/profile.html -->

<table>
    <tr>
        <td>아이디</td>
        {% if user.level == '0'%}
        <td>{{ user.user_id }}(개발자)</td>
        {% elif user.level == '1' %}
        <td>{{ user.user_id }}(관리자)</td>
        {% else %}
        <td>{{ user.user_id }}</td>
        {% endif %}
    </tr>
    <tr>
        <td>이메일</td>
        <td>{{ user.email }}</td>
    </tr>
    <tr>
        <td>이름</td>
        <td>{{ user.name }}</td>
    </tr>
</table>

templates/accountapp/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url '{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'accountapp:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/header.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">

<div class="today_header">
    <div class="nav_wrap" >
        <div class="nav" >
            <a href="{% url 'buildapp:home' %}" class="header_today_logo">&lt;오늘:의 문장&gt;</a>
            <ul class="nav_menu">
                <li class="nav_item"><a href="{% url 'buildapp:write_sentence' %}" class="nav_btn">문장쓰기</a></li>
                <li class="nav_item"><a href="{% url 'buildapp:write_poet' %}" class="nav_btn">글쓰기</a></li>
                <li class="nav_item"><a href="{% url 'buildapp:community' %}" class="nav_btn">커뮤니티</a></li>

                {% if user.is_authenticated %}
                    <li class="nav_item" style="float: right"><a class="nav_btn" href="{% url 'accountapp:logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a></li>
                    <li class="nav_item" style="float: right"><a href="{% url 'profileapp:mypage' %}" class="nav_btn">{{ user.username }}</a></li>
                {% else %}
                    <li class="nav_item" style="float: right"><a href="{% url 'accountapp:create' %}" class="nav_btn">회원가입</a></li>
                    <li class="nav_item" style="float: right"><a href="{% url 'accountapp:login' %}" class="nav_btn">로그인</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</div>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'accountapp:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'accountapp:login' %}">로그인</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>